### PR TITLE
fix the address of qrcode picture

### PR DESCRIPTION
**Pull request by wkcn**
Hi, there.
It seems that the website `https://zh.mxnet.io/blog/` doesn't show the QRcode successfully.
I modify the absolute path of QRCode into the relative path.

Thanks!

### CODE REVIEW

**Comment by hetong007** [comment]
Using relative path causes that the QR code only appears at the footer of first page, but still broken at the 2nd and 3rd. 

Path at the first page: http://127.0.0.1:4000/img/qrcode.jpg
Path at the 2nd page: http://127.0.0.1:4000/page2/img/qrcode.jpg

would you mind to investigate further?

**Comment by hetong007** [comment]
The path for the QR code image should be: https://zh.mxnet.io/blog/img/qrcode.jpg

**Comment by wkcn** [comment]
Thank you! Could we need to modify the base_url: https://github.com/mxnet-zh/blog/blob/master/_config.yml#L13. ?

**Comment by hetong007** [comment]
I think a simple fix is to use `/blog/img/qrcode.jpg`

**Comment by wkcn** [comment]
I have updated the path of QRCode, and the year of copyright.

**Pull request merged**
